// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SignLanguage.ADO
{
    public partial class BadMeaningWords
    {
        public int IdBadMeaningWord { get; set; }
        public int IdGoodMeaningWord { get; set; }
        public string Meaning { get; set; }
    }
}