// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SignLanguage.ADO
{
    public partial class GoodMeaningWords
    {
        public int IdGoodMeaningWord { get; set; }
        public string Meaning { get; set; }
        public string Url { get; set; }
    }
}