// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SignLanguage.ADO
{
    public partial class Users
    {
        public string IdUser { get; set; }
        public string Login { get; set; }
        public DateTime PasswordExpiredDate { get; set; }
        public short UserRole { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string Password { get; set; }
    }
}