// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SignLanguage.ADO
{
    public partial class UsersScoreQuiz
    {
        public int Id { get; set; }
        public string IdUser { get; set; }
        public int HowManyQustion { get; set; }
        public decimal EffectivenessInPercent { get; set; }
    }
}